networks:
  gateway-protocol:
    name: gateway/protocol
  exalton:
    external: true

services:
  redis:
    container_name: gateway-redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - gateway-protocol

  issuer-playground:
    container_name: gateway-issuer-playground
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - ENV_PATH=.env.playground
    ports:
      - 8080:8000
    volumes:
      - ../data:/app/data:ro
    networks:
      - gateway-protocol
      - exalton
